In [1]:
import gym
import random
import numpy as np

In [4]:
env= gym.make("FrozenLake-v0")

/home/shreyash/anaconda3/lib/python3.7/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)


In [5]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

Q_table = np.zeros((state_space_size,action_space_size))
print(Q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
num_episodes = 10000
max_steps_per_episode = 100

alpha = 0.1         #learning-rate
gamma = 0.99        #discount-rate

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [7]:
rewards_all_episodes = []

#Q-learning algorithm

for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        # Epsilon-greedy policy
        exploration_prob = random.uniform(0,1)
        if (exploration_prob > exploration_rate):
            action = np.argmax(Q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)

        Q_table[state,action] =Q_table[state,action] *(1-alpha) + alpha*(reward+ gamma* np.max(Q_table[new_state,:]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
    
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    
    rewards_all_episodes.append(rewards_current_episode)

In [8]:
rewards_per_hundred_episodes = np.split(np.array(rewards_all_episodes), num_episodes/100)
count = 100
print("Average reward per hundred episodes")

for r in rewards_per_hundred_episodes:
    print(count, ":", str(sum(r/100)))
    count +=100

print("\n\n Q_table\n")
print(Q_table)

Average reward per hundred episodes
100 : 0.0
200 : 0.0
300 : 0.01
400 : 0.01
500 : 0.03
600 : 0.02
700 : 0.08
800 : 0.10999999999999999
900 : 0.04
1000 : 0.09
1100 : 0.03
1200 : 0.13999999999999999
1300 : 0.16
1400 : 0.16
1500 : 0.26000000000000006
1600 : 0.25000000000000006
1700 : 0.22000000000000006
1800 : 0.26000000000000006
1900 : 0.2700000000000001
2000 : 0.3300000000000001
2100 : 0.4100000000000002
2200 : 0.34000000000000014
2300 : 0.4100000000000002
2400 : 0.3300000000000001
2500 : 0.45000000000000023
2600 : 0.45000000000000023
2700 : 0.3100000000000001
2800 : 0.5400000000000003
2900 : 0.5700000000000003
3000 : 0.5200000000000002
3100 : 0.5000000000000002
3200 : 0.5400000000000003
3300 : 0.6100000000000003
3400 : 0.5000000000000002
3500 : 0.6400000000000003
3600 : 0.6300000000000003
3700 : 0.5500000000000003
3800 : 0.6300000000000003
3900 : 0.5300000000000002
4000 : 0.6400000000000003
4100 : 0.6100000000000003
4200 : 0.46000000000000024
4300 : 0.5700000000000003
4400 : 0.550000

In [9]:
state = env.reset()
done = False
for step in range(max_steps_per_episode):
    env.render()
    
    action = np.argmax(Q_table[state,:])
    
    new_state, reward, done, info = env.step(action)
    
    if done:
        env.render()
        if reward == 1:
            print("You have reached the goal")
        else:
            print("You fell in a hole")
        break
        
    state = new_state
    
env.close


SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
You have reached the goal


<bound method Wrapper.close of <TimeLimit<FrozenLakeEnv<FrozenLake-v0>>>>